version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    networks:
      - mynetwork  # Usa a mesma rede personalizada
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    networks:
      - mynetwork  # Usa a mesma rede personalizada
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  nginx:
    image: nginx:1.19.0
    restart: always
    networks:
    - mynetwork  # Usa a mesma rede personalizada
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mapeia o arquivo de configuração do Nginx
      - ./wordpress:/usr/share/nginx/html/wordpress  # Mapeia a pasta compartilhada do WordPress 1
    ports:
      - 80:80
    depends_on:
      - wordpress


networks:
  mynetwork:  # Define a rede personalizada 'mynetwork'
